### ISSUE TITLE
any update on this repo?

### ISSUE THREAD

**Issue by xiaods** [smartxworks/virtink#106]
I've noticed that this project hasn't been maintained for quite some time. Is the project still being maintained?

**Comment by fengye87** [comment]
Yep, it will receive bugfixes. But our core team is not putting our efforts on new features since we are happy with current feature set

**Comment by xiaods** [comment]
> Yep, it will receive bugfixes. But our core team is not putting our efforts on new features since we are happy with current feature set

thanks for your reply.  i want to integrate vmm on my k8s engine. so read your project. https://github.com/xiaods/k8e/issues/341

**Comment by maxpain** [comment]
Still unmaintained?

**Comment by fengye87** [comment]
@maxpain We've paused all further feature development on this project, but are accepting PRs for security patches and bug fixes. It's worth mentioning that there's a [fork](https://github.com/nalajala4naresh/ch-vmm) which you may be interested in.
