### ISSUE TITLE
Could we mount hostPath into the virtual machine?

### ISSUE THREAD

**Issue by weixiao-huang** [smartxworks/virtink#48]
Since [kata-containers](https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-use-virtio-fs-with-kata.md) use [virtio-fs](https://virtio-fs.gitlab.io/) to mount hostPath into virtual machine, is there any method to mount hostPath into the VM?

**Comment by fengye87** [comment]
That's an interesting feature. The general idea is to mount a host FS (hostPath or whatever FS mode volume) to the VM right? It mostly would depend on whether CH supports virtio-fs. We'll dig into this.
