### ISSUE TITLE
DataVolume GC cause VM deployment failure

### ISSUE THREAD

**Issue by lobshunter** [smartxworks/virtink#62]
Recent version of CDI will [garbage collect completed DataVolume](https://github.com/kubevirt/containerized-data-importer/pull/2233/files). For VM uses DataVolume, virtink waits its DataVolume import to be completed before starting the VM. But with default CDI deployment, DataVolume will be GCed once completed. Hence virtink fails deploy VM with `build VM Pod: DataVolume.cdi.kubevirt.io "cdi-volume" not found` error.

Perhaps it's worth mentioning this in CDI VM example. Tuning `.spec.config.dataVolumeTTLSeconds` of `cdi.kubevirt.io/v1beta1` works.(or adapting virtink to CDI's GC action?)

**Comment by scuzhanglei** [comment]
Thanks for your report, we have notice this issue and https://github.com/smartxworks/virtink/pull/61 will fix it.
