### ISSUE TITLE
Does not work in a KinD cluster

### ISSUE THREAD

**Issue by ManasPecenek** [smartxworks/virtink#72]
Even though the VM I used to install the KinD cluster satisfies the conditions, it does not work. When I run "kubectl get vm" I can see it running, and also the relevant pod is running too. However, I cannot ssh into the virtink VM. For the record, I successfully created a VM inside a KinD cluster via KubeVirt. I wonder what the difference is and what actually causes it.

**Comment by fengye87** [comment]
@ManasPecenek Could you share your VM yaml and the rootfs Dockerfile if any? And where were you trying to SSH from? Outside the KinD cluster or inside?

**Comment by ManasPecenek** [comment]
@fengye87 My vm yaml is [the one](https://github.com/smartxworks/virtink#create-a-vm) in the documentation. And I am trying to ssh like mentioned [here](https://github.com/smartxworks/virtink#access-the-vm-via-ssh), creating a pod, installing OpenSSH and then sshing into the VM. But doesn't work, I even cannot ping the vm inside that pod

**Comment by fengye87** [comment]
@ManasPecenek I guess you are using KinD's default CNI? This CNI was known not to work with Virtink's bridge network. Virtink should work in KinD with CNIs like Calico.

**Comment by ManasPecenek** [comment]
@fengye87 Thanks for the reminder. I will try with calico this time

**Comment by ManasPecenek** [comment]
@fengye87 It worked with Calico. Huge thanks

**Comment by ManasPecenek** [comment]
Solved by using Calico instead of KinD's default CNI
`networking:
  disableDefaultCNI: true # disable kindnet
  podSubnet: 192.168.0.0/16 # set to Calico's default subnet`
